INSERT INTO role (id, name) VALUES (1, 'ADMIN');
INSERT INTO role (id, name) VALUES (2, 'CA_USER');
INSERT INTO role (id, name) VALUES (3, 'END_USER');

INSERT INTO users (email, password, first_name, last_name, organization, enabled, role_id) VALUES ('admin@pki-system.com', '$2a$10$ChxeCMeH3bWi7j8J/YFONuF0ZCmFZv6BLi/wp49l1VZCTTLYbxAu2', 'System', 'Administrator', 'MainOrg', true, 1);
INSERT INTO users (email, password, first_name, last_name, organization, enabled, role_id) VALUES ('kiss.akos02@gmail.com', '$2a$12$1dAGhd4gVXjcLACrRHPJzOSwqVAcpIhgwDPxVUKU3eSTx7HcGXz9y', 'Akos', 'Kiss', 'AkorORG', true, 3);
INSERT INTO users (email, password, first_name, last_name, organization, enabled, role_id) VALUES ('causer@pki-system.com', '$2a$10$BDOnxr1mEDc9VMDAqq9tSOcWzeCFbFmW5eZC8wEyPoJ.SuU83.Mlq', 'CA', 'User', 'CA-Org', true, 2);
INSERT INTO users (email, password, first_name, last_name, organization, enabled, role_id) VALUES ('eeuser@pki-system.com', '$2a$10$BDOnxr1mEDc9VMDAqq9tSOcWzeCFbFmW5eZC8wEyPoJ.SuU83.Mlq', 'Jana', 'Jankovic', 'FTN', true, 3);

UPDATE users SET symmetric_key = 'KcfRHpE5wrRgWk7gRvLSK9ZKk1FXnJkigHD32ZUqT2o=' WHERE email = 'causer@pki-system.com';
UPDATE users SET symmetric_key = 'KcfRHpE5wrRgWk7gRvLSK9ZKk1FXnJkigHD32ZUqT2o=' WHERE email = 'admin@pki-system.com';

INSERT INTO certificates(serial_number, subject_common_name, subject_surname, subject_givenname, subject_organization, subject_organizational_unit, subject_country, issuer_common_name, issuer_organization, not_before, not_after, type, parent_certificate_id, revoked, revoked_at, revocation_reason, crl_path, key_store_path, key_store_password, owner_id) VALUES ('1001', 'SystemRootCA', 'AdminSurname', 'AdminGivenName','MainOrg', 'IT Department', 'RS','SystemRootCA', 'MainOrg',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '5 years','ROOT', NULL,false, NULL, NULL, NULL,'keystores/1001.p12', 'JK9D+znt/rHlgEQ3cNOvMS1zznlEA6P1nfekwCw0EoE=', 1);
INSERT INTO certificates(serial_number, subject_common_name, subject_surname, subject_givenname, subject_organization, subject_organizational_unit, subject_country, issuer_common_name, issuer_organization, not_before, not_after, type, parent_certificate_id, revoked, revoked_at, revocation_reason, crl_path, key_store_path, key_store_password, owner_id) VALUES ('1002', 'CA-Org Intermediate CA', NULL, NULL, 'CA-Org', 'Security Division', 'RS','SystemRootCA', 'MainOrg',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '3 years','INTERMEDIATE', 1,false, NULL, NULL, NULL,'keystores/1002.p12', 'JK9D+znt/rHlgEQ3cNOvMS1zznlEA6P1nfekwCw0EoE=', 3);
INSERT INTO certificates(serial_number, subject_common_name, subject_surname, subject_givenname, subject_organization, subject_organizational_unit, subject_country, issuer_common_name, issuer_organization, not_before, not_after, type, parent_certificate_id, revoked, revoked_at, revocation_reason, crl_path, key_store_path, key_store_password, owner_id) VALUES ('1003', 'CA-Org Web Servers CA', NULL, NULL,'CA-Org', 'Web Infrastructure', 'RS','CA-Org Intermediate CA', 'CA-Org',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '1 year','INTERMEDIATE', 2,false, NULL, NULL, NULL,'keystores/1003.p12', 'JK9D+znt/rHlgEQ3cNOvMS1zznlEA6P1nfekwCw0EoE=', 3);
